import { generateVatReport } from "@/lib/actions/vat-report";
import { getSettings } from "@/lib/numbering";
import { companyFromSettings } from "@/lib/company";
import { renderToBuffer } from "@react-pdf/renderer";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { formatMoney, formatDate } from "@/lib/money";
import { NextRequest } from "next/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 9, fontFamily: "Helvetica", color: "#16212E" },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", marginBottom: 4, color: "#0E2A47" },
  subtitle: { fontSize: 10, color: "#5B6472", marginBottom: 20 },
  row: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#EEF1F5", paddingVertical: 4 },
  header: { backgroundColor: "#F4F6F8", borderBottomWidth: 1, borderBottomColor: "#D8DEE6", paddingVertical: 5 },
  th: { fontSize: 7, letterSpacing: 1, textTransform: "uppercase", color: "#5B6472", fontWeight: "bold" },
  td: { fontSize: 9 },
  colType: { width: "10%" },
  colNumber: { width: "14%" },
  colDate: { width: "12%" },
  colClient: { width: "22%" },
  colVat: { width: "10%" },
  colNet: { width: "16%", textAlign: "right" },
  colTax: { width: "16%", textAlign: "right" },
  kpiRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 20 },
  kpiBox: { width: "30%", padding: 10, borderWidth: 0.5, borderColor: "#D8DEE6", borderRadius: 4 },
  kpiLabel: { fontSize: 7, letterSpacing: 1, textTransform: "uppercase", color: "#5B6472" },
  kpiValue: { fontSize: 14, fontFamily: "Helvetica-Bold", marginTop: 4, color: "#0E2A47" },
  footer: { marginTop: 20, borderTopWidth: 1, borderTopColor: "#D8DEE6", paddingTop: 10, fontSize: 8, color: "#5B6472" },
});

function VatPdf({ report, company }: { report: Awaited<ReturnType<typeof generateVatReport>>; company: ReturnType<typeof companyFromSettings> }) {
  const money = (v: number) => formatMoney(v, company.currency || "R");

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>VAT Report</Text>
        <Text style={styles.subtitle}>
          {formatDate(report.from)} - {formatDate(report.to)} · {report.basis} basis
        </Text>

        <View style={styles.kpiRow}>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Output Tax</Text>
            <Text style={styles.kpiValue}>{money(report.totalOutputTax)}</Text>
          </View>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Input Tax</Text>
            <Text style={styles.kpiValue}>{money(report.totalInputTax)}</Text>
          </View>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>VAT Payable</Text>
            <Text style={[styles.kpiValue, { color: report.vatPayable >= 0 ? "#C53030" : "#16A34A" }]}>
              {money(report.vatPayable)}
            </Text>
          </View>
        </View>

        <View style={[styles.row, styles.header]}>
          <Text style={[styles.th, styles.colType]}>Type</Text>
          <Text style={[styles.th, styles.colNumber]}>Number</Text>
          <Text style={[styles.th, styles.colDate]}>Date</Text>
          <Text style={[styles.th, styles.colClient]}>Client / Category</Text>
          <Text style={[styles.th, styles.colVat]}>VAT</Text>
          <Text style={[styles.th, styles.colNet]}>Net</Text>
          <Text style={[styles.th, styles.colTax]}>Tax</Text>
        </View>
        {report.lines.map((l, i) => (
          <View key={i} style={styles.row}>
            <Text style={[styles.td, styles.colType]}>{l.kind}</Text>
            <Text style={[styles.td, styles.colNumber]}>{l.number}</Text>
            <Text style={[styles.td, styles.colDate]}>{formatDate(l.date)}</Text>
            <Text style={[styles.td, styles.colClient]}>{l.clientOrSupplier}</Text>
            <Text style={[styles.td, styles.colVat]}>{l.vatTreatment}</Text>
            <Text style={[styles.td, styles.colNet]}>{money(l.netAmount)}</Text>
            <Text style={[styles.td, styles.colTax]}>{money(l.taxAmount)}</Text>
          </View>
        ))}

        <View style={styles.footer}>
          <Text>Generated by {company.companyName} · Ledger Invoicing</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const from = searchParams.get("from") || new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10);
  const to = searchParams.get("to") || new Date().toISOString().slice(0, 10);
  const basis = (searchParams.get("basis") as "accrual" | "cash") || "accrual";

  const settings = await getSettings();
  const report = await generateVatReport(from, to, basis);

  const buffer = await renderToBuffer(
    <VatPdf report={report} company={companyFromSettings(settings)} />
  );

  return new Response(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="vat-report-${from}-to-${to}.pdf"`,
    },
  });
}
